import { Container, Task } from "@aws-sdk/client-ecs";
import { Event, EventsList } from "aws-sdk/clients/cloudtrail";
import { FunctionConfiguration, FunctionList } from "aws-sdk/clients/lambda";

export interface AWSLambdaFunctionList {
  Functions: FunctionList;
  region: string;
}

export interface CloudTrailEventDescriptionList {
  Events: EventsList;
  region: string;
}

export interface AWSLambdaTrailData {
  region: string;
  lambda: FunctionConfiguration;
  trailEvents: EventsList;
}

export interface OXAWSRunningTaskData {
  region: string;
  clusterArn: string;
  taskDefinition: Task[];
}

export interface OXAWSImageTrailData {
  region: string;
  containerImage: Container;
  trailEvents: Event;
}

//
// AWS Resources
//
export interface AWSResources {
  ResourceTagMappingList: ResourceTagMappingList[];
  PaginationToken?: string | undefined;
}

export interface ResourceTagMappingList {
  ResourceARN?: string;
  Tags?: Tag[];
}

export interface Tag {
  Key: string;
  Value: string;
}

// ECR image type
// Generated by https://quicktype.io

export interface AWSEcrRepository {
  repositoryArn: string;
  registryId: string;
  repositoryName: string;
  repositoryUri: string;
  createdAt: string;
  imageTagMutability: string;
  imageScanningConfiguration: ImageScanningConfiguration;
  encryptionConfiguration: EncryptionConfiguration;
}

export interface EncryptionConfiguration {
  encryptionType: string;
}

export interface ImageScanningConfiguration {
  scanOnPush: boolean;
}

export type FunctionArn = string;
export type AWSRegion = string;
export type AWSTaskARN = string;
export type ImageName = string;
export type ImageDigest = string;

export interface Instances {
  [instanceId: string]: InstanceImages;
}

export interface ParsedImages {
  imageId: string;
  image: string;
  tag: string;
}

export interface InstanceImages {
  [imageId: string]: InstanceImage;
}

export interface InstanceImage {
  image: string;
  tag: string;
  created: string;
  sha: string;
  region: string;
  architecture: string;
  // manifestSha: string;
}

export interface ParsedImages {
  imageId: string;
  image: string;
  tag: string;
}

export type AWSResourceType = "ecs" | "lambda" | "ec2" | "dkr";
export type AWSDataTrailType = "data" | "trail" | "lastUpdateTime";
export interface AWSResourceTypeData {
  id: AWSResourceType; // ecs/ec2/lambda
  account: string;
  region: string;
  resourceArn: string;
}
export interface AWSResource {
  id: string; // Resource ARN
  type: AWSResourceType; // ecs/ec2/lambda
  trail: string; // stringified cloud trail data
  data: string; // stringified cloud data (depends on the data)
  accounts: string[]; // every account that has access to this resource (e.g 956424807926)
  lastUpdateTime: string;
  region: string;
  bypass: boolean; // For caching purposes, when we want to skip this resource
}

export interface AWSResourcesStatistics {
  resourceCount: number;
  resourcesWithData: number;
  resourcesWithTrails: number;
  resourcesFiltered: number;
  resourceNotFound: number; // resources not found by tagging engine
  resourcesCached: number;
  resourcesWithMultipleAccounts: number;
}

export type AWSResourceId = string;
export type AWSEcrRepositoryName = string;
export type ContainerImageName = string;

//eks

//not in use right now

export interface ClusterDescription {
  cluster: Cluster;
}
export interface Cluster {
  arn: string;
  certificateAuthority: CertificateAuthority;
  createdAt: string;
  endpoint: string;
  name: string;
  platformVersion: string;
  roleArn: string;
  status: string;
  tags: Tags;
  version: string;
}

export interface CertificateAuthority {
  data: string;
}

export interface Tags {}

//namespace
export interface Events {}

export interface NamespaceData {
  kind: string;
  apiVersion: APIVersion;
  metadata: DataMetadata;
  items: Item[];
}

export enum APIVersion {
  V1 = "v1",
}

export interface ItemMetadata {
  name: string;
  uid: string;
  resourceVersion: string;
  creationTimestamp: string;
  labels: Labels;
  managedFields: ManagedField[];
}

export interface Labels {
  "kubernetes.io/metadata.name": string;
  name?: string;
}

export interface ManagedField {
  apiVersion: APIVersion;
  time: string;
}

//pods
export interface PodsData {
  kind: string;
  apiVersion: APIVersion;
  metadata: DataMetadata;
  items: Item[];
}

export interface Item {
  metadata: ItemMetadata;
  spec: Spec;
  status: Status;
}

export interface ItemMetadata {
  name: string;
  uid: string;
  resourceVersion: string;
  creationTimestamp: string;
  managedFields: ManagedField[];
}

export interface ManagedField {
  apiVersion: APIVersion;
  time: string;
}

export interface Status {
  containerStatuses: ContainerStatuses[];
  startTime?: string;
}

export interface ContainerStatuses {
  image: string;
  imageID: string;
}

export interface DataMetadata {
  resourceVersion: string;
}

//deployments

export interface TartuGecko {}

export interface DeploymentsData {
  kind: string;
  apiVersion: string;
  metadata: DataMetadata;
  items: Item[];
}
export interface Item {
  metadata: ItemMetadata;
  spec: Spec;
  status: Status;
}

export interface Spec {
  replicas?: number;
  template?: Template;
  strategy?: Strategy;
  revisionHistoryLimit?: number;
  progressDeadlineSeconds?: number;
  containers?: Containerr[];
}

export interface Strategy {
  type: string;
  rollingUpdate: RollingUpdate;
}

export interface RollingUpdate {
  maxUnavailable: string;
  maxSurge: string;
}

export interface Template {
  metadata: TemplateMetadata;
  spec: TemplateSpec;
}

export interface TemplateMetadata {
  creationTimestamp: null;
  labels: Labels;
}

export interface TemplateSpec {
  containers: Containerr[];
  restartPolicy: string;
  terminationGracePeriodSeconds: number;
  dnsPolicy: string;
  serviceAccountName: string;
  serviceAccount: string;
  schedulerName: string;
  priorityClassName: string;
}

export interface Containerr {
  imageID: string;
  name: string;
  image: string;
  command: string[];
  args: string[];
  resources: TartuGecko;
  terminationMessagePath: string;
  terminationMessagePolicy: string;
  imagePullPolicy: string;
}
